export const CODE_LANGUAGES = [
  "plaintext",
  "javascript",
  "typescript",
  "jsx",
  "tsx",
  "python",
  "html",
  "css",
  "scss",
  "json",
  "java",
  "c",
  "cpp",
  "csharp",
  "objectivec",
  "ruby",
  "go",
  "rust",
  "swift",
  "kotlin",
  "dart",
  "php",
  "sql",
  "bash",
  "markdown",
  "xml",
  "yaml",
  "graphql",
  "lua",
  "perl",
  "scala",
  "haskell",
  "elixir",
  "r",
  "dockerfile",
] as const;

export const LANGUAGE_LABELS: Record<string, string> = {
  plaintext: "Plain Text",
  javascript: "JavaScript",
  typescript: "TypeScript",
  jsx: "React JSX",
  tsx: "React TSX",
  python: "Python",
  html: "HTML",
  css: "CSS",
  scss: "SCSS",
  json: "JSON",
  java: "Java",
  c: "C",
  cpp: "C++",
  csharp: "C#",
  objectivec: "Objective-C",
  ruby: "Ruby",
  go: "Go",
  rust: "Rust",
  swift: "Swift",
  kotlin: "Kotlin",
  dart: "Dart",
  php: "PHP",
  sql: "SQL",
  bash: "Bash / Shell",
  markdown: "Markdown",
  xml: "XML",
  yaml: "YAML",
  graphql: "GraphQL",
  lua: "Lua",
  perl: "Perl",
  scala: "Scala",
  haskell: "Haskell",
  elixir: "Elixir",
  r: "R",
  dockerfile: "Dockerfile",
};

const EXTENSION_TO_LANGUAGE: Record<string, string> = {
  js: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  jsx: "jsx",
  ts: "typescript",
  mts: "typescript",
  cts: "typescript",
  tsx: "tsx",
  py: "python",
  pyw: "python",
  html: "html",
  htm: "html",
  css: "css",
  scss: "scss",
  sass: "scss",
  less: "css",
  json: "json",
  java: "java",
  c: "c",
  h: "c",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  hpp: "cpp",
  hh: "cpp",
  cs: "csharp",
  m: "objectivec",
  mm: "objectivec",
  rb: "ruby",
  go: "go",
  rs: "rust",
  swift: "swift",
  kt: "kotlin",
  kts: "kotlin",
  dart: "dart",
  php: "php",
  sql: "sql",
  sh: "bash",
  bash: "bash",
  zsh: "bash",
  md: "markdown",
  mdx: "markdown",
  xml: "xml",
  svg: "xml",
  yaml: "yaml",
  yml: "yaml",
  graphql: "graphql",
  gql: "graphql",
  lua: "lua",
  pl: "perl",
  pm: "perl",
  scala: "scala",
  sc: "scala",
  hs: "haskell",
  ex: "elixir",
  exs: "elixir",
  r: "r",
  dockerfile: "dockerfile",
  txt: "plaintext",
  toml: "plaintext",
  ini: "plaintext",
  cfg: "plaintext",
  env: "plaintext",
};

export function inferLanguageFromTitle(title: string): string | null {
  if (!title || !title.includes(".")) return null;
  const parts = title.split(".");
  const ext = parts[parts.length - 1].toLowerCase();
  if (title.toLowerCase() === "dockerfile") return "dockerfile";
  return EXTENSION_TO_LANGUAGE[ext] || null;
}
